const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 15.99,
    img: 'https://media.istockphoto.com/id/161170090/photo/pancakes-with-berries-and-maple-syrup.jpg?s=612x612&w=0&k=20&c=8EctScsN7q5UmxeXPNBnYN1eFmJmgmp2bE0OIq_czwM=',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'diner double',
    category: 'lunch',
    price: 13.99,
    img: 'https://media.istockphoto.com/id/1269259946/photo/double-cheese-burger-with-tomatoes-onions-and-salad.jpg?s=612x612&w=0&k=20&c=qOiqTcpXdnbxMDpM_UtVJhRPrAdGIzPj8m70hT0kCxM=',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'shakes',
    price: 6.99,
    img: 'https://media.istockphoto.com/id/951396042/photo/chocolate-mocha-frappe-whipped-creme-topping.jpg?s=612x612&w=0&k=20&c=VnogGAco2kT9ke-4NpjLCctofv0iTJ64r9jKxlo2LoI=',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: 'https://media.istockphoto.com/id/659293864/photo/chocolate-smoothie-with-banana.jpg?s=612x612&w=0&k=20&c=y5d2fUCqQwLOq38yWyzY6AqcC5nLg59d_J3t2Dc1Lm4=',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: 'https://media.istockphoto.com/id/1129381764/photo/frying-egg-in-a-cooking-pan-in-domestic-kitchen.jpg?s=612x612&w=0&k=20&c=bpQaB0wG8KHw5-PvKdybSfeWf_jNF8wihRYj2zQEhsQ=',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: 'https://media.istockphoto.com/id/683194578/photo/vanilla-milkshake-with-chocolate-cookies-and-black-straw.jpg?s=612x612&w=0&k=20&c=2h340QVdwTdtqeJgcO7fBkQNevTmiDjMx6jlQLbpacw=',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: 'https://media.istockphoto.com/id/178705097/photo/beer-and-burger.jpg?s=612x612&w=0&k=20&c=1QhUw7aDhWkgSGo8Y-zBo-TSIlXxYRTCbZPnhOgkDS4=',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: 'https://media.istockphoto.com/id/931308812/photo/selection-of-american-food.jpg?s=612x612&w=0&k=20&c=7-2Glc2qVkrWdLaqXwLnNoJLUvc2vMz_QpDTKDcmYiY=',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'quarantine buddy',
    category: 'shakes',
    price: 16.99,
    img: 'https://media.istockphoto.com/id/537522498/photo/freshly-blended-fruit-smoothies-of-various-colors-and-tastes.jpg?s=612x612&w=0&k=20&c=p-BeboePGQOBWVTCYETfCQzhMiOVyf2MVnSkV6aIUyQ=',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
