export default {
"login": "Abhishek-chaurasiya",
"id": 107196798,
"node_id": "U_kgDOBmOxfg",
"avatar_url": "https://avatars.githubusercontent.com/u/107196798?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Abhishek-chaurasiya",
"html_url": "https://github.com/Abhishek-chaurasiya",
"followers_url": "https://api.github.com/users/Abhishek-chaurasiya/followers",
"following_url": "https://api.github.com/users/Abhishek-chaurasiya/following{/other_user}",
"gists_url": "https://api.github.com/users/Abhishek-chaurasiya/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Abhishek-chaurasiya/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Abhishek-chaurasiya/subscriptions",
"organizations_url": "https://api.github.com/users/Abhishek-chaurasiya/orgs",
"repos_url": "https://api.github.com/users/Abhishek-chaurasiya/repos",
"events_url": "https://api.github.com/users/Abhishek-chaurasiya/events{/privacy}",
"received_events_url": "https://api.github.com/users/Abhishek-chaurasiya/received_events",
"type": "User",
"site_admin": false,
"name": "Abhishek Chaurasiya",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "Software Developer\r\n",
"twitter_username": null,
"public_repos": 14,
"public_gists": 0,
"followers": 1,
"following": 1,
"created_at": "2022-06-09T13:48:43Z",
"updated_at": "2022-12-19T09:31:23Z"
}